# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'


networks:
  byfn:
services:


  ca0.org1.ideal.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: ca_peerOrg1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.ideal.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/dce4e54fae0b018d79d124a6e7cbdf47c0421def646124d9d323d75880d2f273_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.ideal.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/dce4e54fae0b018d79d124a6e7cbdf47c0421def646124d9d323d75880d2f273_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.ideal.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - byfn

  ca0.org2.ideal.com:
    image: hyperledger/fabric-ca:x86_64-1.1.0
    container_name: ca_peerOrg2
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.ideal.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f35bb473af4fb30af865ba9490d12c2dd76973060b232755b24d2989d06b9394_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.ideal.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/f35bb473af4fb30af865ba9490d12c2dd76973060b232755b24d2989d06b9394_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.ideal.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - byfn

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5984:5984"
    networks:
      - byfn

  peer0.org1.ideal.com:
    container_name: peer0.org1.ideal.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.ideal.com
      - CORE_PEER_ADDRESS=peer0.org1.ideal.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.ideal.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.ideal.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.ideal.com/peers/peer0.org1.ideal.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.ideal.com/peers/peer0.org1.ideal.com/tls:/etc/hyperledger/fabric/tls
        ###挂载账本数据存储到宿主机上
        - ./peer0.org1.ideal.com/:/var/hyperledger/production/
    ports:
      - 7051:7051
      - 7053:7053
    extra_hosts:
      - "orderer1.ideal.com:172.31.24.32"
      - "orderer2.ideal.com:172.31.24.32"
      - "orderer3.ideal.com:172.31.24.32"
    depends_on:
      - couchdb0
    networks:
      - byfn

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6984:5984"
    networks:
      - byfn

  peer1.org1.ideal.com:
    container_name: peer1.org1.ideal.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.ideal.com
      - CORE_PEER_ADDRESS=peer1.org1.ideal.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.ideal.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.ideal.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.ideal.com/peers/peer1.org1.ideal.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.ideal.com/peers/peer1.org1.ideal.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    extra_hosts:
      - "orderer1.ideal.com:172.31.24.32"
      - "orderer2.ideal.com:172.31.24.32"
      - "orderer3.ideal.com:172.31.24.32"
    depends_on:
      - couchdb1
    networks:
      - byfn

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:x86_64-0.4.6
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "7984:5984"
    networks:
      - byfn

  peer0.org2.ideal.com:
    container_name: peer0.org2.ideal.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.ideal.com
      - CORE_PEER_ADDRESS=peer0.org2.ideal.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.ideal.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.ideal.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.ideal.com/peers/peer0.org2.ideal.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.ideal.com/peers/peer0.org2.ideal.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    extra_hosts:
      - "orderer1.ideal.com:172.31.24.32"
      - "orderer2.ideal.com:172.31.24.32"
      - "orderer3.ideal.com:172.31.24.32"
    depends_on:
      - couchdb2
    networks:
      - byfn

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8984:5984"
    networks:
      - byfn

  peer1.org2.ideal.com:
    container_name: peer1.org2.ideal.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.ideal.com
      - CORE_PEER_ADDRESS=peer1.org2.ideal.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.ideal.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.ideal.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.ideal.com/peers/peer1.org2.ideal.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.ideal.com/peers/peer1.org2.ideal.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053
    extra_hosts:
      - "orderer1.ideal.com:172.31.24.32"
      - "orderer2.ideal.com:172.31.24.32"
      - "orderer3.ideal.com:172.31.24.32"
    depends_on:
      - couchdb3
    networks:
      - byfn
      
