# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:

  kafka1.ideal.com:
    container_name: kafka1.ideal.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1.ideal.com:9092
    ports:
      - 9092:9092
      - 9093:9093
    extra_hosts:
      - "zookeeper1.ideal.com:172.31.24.34"
      - "zookeeper2.ideal.com:172.31.24.34"
      - "zookeeper3.ideal.com:172.31.24.34"
      - "kafka1.ideal.com:172.31.24.33"
      - "kafka2.ideal.com:172.31.24.33"
      - "kafka3.ideal.com:172.31.24.33"
      - "kafka4.ideal.com:172.31.24.33"
    networks:
      - byfn 

  kafka2.ideal.com:
    container_name: kafka2.ideal.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2.ideal.com:8092
    ports:
      - 8092:9092
      - 8093:9093
    extra_hosts:
      - "zookeeper1.ideal.com:172.31.24.34"
      - "zookeeper2.ideal.com:172.31.24.34"
      - "zookeeper3.ideal.com:172.31.24.34"
      - "kafka1.ideal.com:172.31.24.33"
      - "kafka2.ideal.com:172.31.24.33"
      - "kafka3.ideal.com:172.31.24.33"
      - "kafka4.ideal.com:172.31.24.33"
    networks:
      - byfn 


  kafka3.ideal.com:
    container_name: kafka3.ideal.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3.ideal.com:7092
    ports:
      - 7092:9092
      - 7093:9093
    extra_hosts:
      - "zookeeper1.ideal.com:172.31.24.34"
      - "zookeeper2.ideal.com:172.31.24.34"
      - "zookeeper3.ideal.com:172.31.24.34"
      - "kafka1.ideal.com:172.31.24.33"
      - "kafka2.ideal.com:172.31.24.33"
      - "kafka3.ideal.com:172.31.24.33"
      - "kafka4.ideal.com:172.31.24.33"
    networks:
      - byfn 

  kafka4.ideal.com:
    container_name: kafka4.ideal.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=4
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka4.ideal.com:6092
    ports:
      - 6092:9092
      - 6093:9093
    extra_hosts:
      - "zookeeper1.ideal.com:172.31.24.34"
      - "zookeeper2.ideal.com:172.31.24.34"
      - "zookeeper3.ideal.com:172.31.24.34"
      - "kafka1.ideal.com:172.31.24.33"
      - "kafka2.ideal.com:172.31.24.33"
      - "kafka3.ideal.com:172.31.24.33"
      - "kafka4.ideal.com:172.31.24.33"
    networks:
      - byfn 
      
